name: OSV Scanner

on:
  push:
  pull_request:

jobs:
  osv-scan:
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@main
    permissions:
      contents: read
      security-events: write
    with:
      scan-args: |
        --recursive .